### ISSUE TITLE
at com.teragrep.rlp_03.RelpServerSocket.processRead(RelpServerSocket.java:98) Maximum lock count exceeded

### ISSUE THREAD

**Issue by kortemik** [teragrep/rlp_03#1]
```
Exception in thread "Thread-1" java.lang.Error: Maximum lock count exceeded
        at java.util.concurrent.locks.ReentrantLock$Sync.nonfairTryAcquire(ReentrantLock.java:141)
        at java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:365)
        at com.teragrep.rlp_03.RelpServerSocket.processRead(RelpServerSocket.java:98)
        at com.teragrep.rlp_03.SocketProcessor.grandSelector(SocketProcessor.java:201)
        at com.teragrep.rlp_03.SocketProcessor.lambda$run$0(SocketProcessor.java:124)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by kortemik** [comment]
fixed in 1.0.2
