### ISSUE TITLE
EventLoop may terminate in case of a disconnect

### ISSUE THREAD

**Issue by kortemik** [teragrep/rlp_03#160]
**Description**

when a connection is disrupted following may happen:
```
        at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
        at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
        at java.base/java.nio.channels.SelectionKey.isAcceptable(SelectionKey.java:425)
        at com.teragrep.rlp_03.eventloop.EventLoop.poll(EventLoop.java:137)
        at com.teragrep.rlp_03.eventloop.EventLoop.run(EventLoop.java:190)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

(EventLoop.java:137) has
```
if (selectionKey.isAcceptable()) {
```

operations on selectionKey in the poll loop may trigger CancelledKeyException which are of a IOException type which will further cause EventLoop to terminate with an UncheckedIOException(ioException);

**Comment by kortemik** [comment]
@StrongestNumber9 case of the ^C which you managed to nicely spot!
