### ISSUE TITLE
OutOfMemoryError and IllegalArgumentException: EstablishedContextStub does not implement this when flooding connections

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#163]
**Describe the bug**

Running current development version of cfe_35 with JMX flags causes this when flooded with connections

```sh
14.05.2024 15:09:48.244 [INFO] [org.eclipse.jetty.server.Server] [main] Started Server@31bcf236{STARTING}[10.0.15,sto=0] @768ms
May 14, 2024 3:10:04 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop run
WARNING: RMI TCP Accept-9011: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9011] throws
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
        at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
        at java.base/java.lang.Thread.run(Thread.java:829)

Exception in thread "Thread-0" java.lang.IllegalArgumentException: EstablishedContextStub does not implement this
        at com.teragrep.rlp_03.channel.context.EstablishedContextStub.close(EstablishedContextStub.java:64)
        at com.teragrep.rlp_03.eventloop.EventLoop.close(EventLoop.java:173)
        at com.teragrep.rlp_03.eventloop.EventLoop.run(EventLoop.java:202)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
 
**Expected behavior**

Works normally
 
**How to reproduce**

Ran development version of cfe_35 with jmxremote settings

`/usr/lib/jvm/jre-11/bin/java -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9011 -Djava.rmi.server.hostname=localhost -DserverThreads=64 -Dkin02TruncationLength=1024 -Dcfe16TruncationLength=1024 -DlistenPort=601 -Dcfe07LookupPath=cfe07Lookups/ -Dcfe16LookupPath=cfe16Lookups/ -Dkin02LookupPath=kin02Lookups/ -DroutingTargetsConfig=targets.json -DprometheusPort=1234 -Dlog4j2.configurationFile=file:log4j2.xml -jar /root/cfe_35.jar`

Flooded connections with tcpflood

`/opt/Fail-Safe/rsyslog/rsyslog/bin/tcpflood -t 127.0.0.1 -p 601 -T relp-plain -c 10000 -Y`

**Software version**

I assume rlp_03 version 7.0.1

**Comment by kortemik** [comment]
fixed EstablishedContextStub in main_tx_frame_fragments, same goes for OOM
