### ISSUE TITLE
ReadMe example code can't handle multiple connections

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#168]
**Describe the bug**

First connection works fine, second connection breaks down

```
java.lang.IllegalArgumentException: frame txn not sequencing
	at com.teragrep.rlp_03.frame.delegate.SequencingDelegate.accept(SequencingDelegate.java:85)
	at com.teragrep.rlp_03.frame.delegate.DefaultFrameDelegate.accept(DefaultFrameDelegate.java:77)
	at com.teragrep.rlp_03.channel.context.RelpReadImpl.processFrame(RelpReadImpl.java:234)
	at com.teragrep.rlp_03.channel.context.RelpReadImpl.run(RelpReadImpl.java:147)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
 
**Expected behavior**

Works normally

**How to reproduce**

Send records, open new connection and send more records

**Software version**

rlp_03 7.0.2

**Comment by kortemik** [comment]
duplicate with #105
