### ISSUE TITLE
Infinite loop in runServerTest when relp connections are not gracefully terminated

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#30]
Testing tool with rlp_01 and multiple threads sending 1 event batches in busy loop -> kill the program and this is what server gets stuck in:

```sh
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:411)
        at com.teragrep.rlp_03.RelpServerPlainSocket.read(RelpServerPlainSocket.java:164)
        at com.teragrep.rlp_03.MessageReader.readRequest(MessageReader.java:109)
        at com.teragrep.rlp_03.RelpServerPlainSocket.processRead(RelpServerPlainSocket.java:102)
        at com.teragrep.rlp_03.SocketProcessor.processReadWriteClose(SocketProcessor.java:421)
        at com.teragrep.rlp_03.SocketProcessor.runMTMessageSelector(SocketProcessor.java:381)
        at com.teragrep.rlp_03.SocketProcessor.lambda$runMultiThreaded$0(SocketProcessor.java:235)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:411)
        at com.teragrep.rlp_03.RelpServerPlainSocket.read(RelpServerPlainSocket.java:164)
        at com.teragrep.rlp_03.MessageReader.readRequest(MessageReader.java:109)
        at com.teragrep.rlp_03.RelpServerPlainSocket.processRead(RelpServerPlainSocket.java:102)
        at com.teragrep.rlp_03.SocketProcessor.processReadWriteClose(SocketProcessor.java:421)
        at com.teragrep.rlp_03.SocketProcessor.runMTMessageSelector(SocketProcessor.java:381)
        at com.teragrep.rlp_03.SocketProcessor.lambda$runMultiThreaded$0(SocketProcessor.java:235)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by StrongestNumber9** [comment]
The issue seems to be in this
https://github.com/teragrep/rlp_03/blob/85373215084be8a9f87f7e674972296650067e40/src/main/java/com/teragrep/rlp_03/RelpServerPlainSocket.java#L101-L106
Write should also be handled in 
https://github.com/teragrep/rlp_03/blob/85373215084be8a9f87f7e674972296650067e40/src/main/java/com/teragrep/rlp_03/RelpServerPlainSocket.java#L130-L135

Current implementation leaves them in endless loops that significantly slows down processing

**Comment by kortemik** [comment]
Please change the exception print to
```
LOGGER.trace(e.toString());
```

and assign
```
cop = ConnectionOperation.CLOSE;
```

ti 7. helmik. 2023 klo 15.02 Strongest Number 9 ***@***.***>
kirjoitti:

**Comment by StrongestNumber9** [comment]
Seems to be working, I opened a PR for it
